# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  name: dockernewagent

variables:
  imageName: devops-life-app
  containerName: devops-life-container
  tag: $(Build.BuildId)

stages:
- stage: BuildAndDeploy
  displayName: Build and Deploy Docker

  jobs:
  - job: DockerBuild
    displayName: Docker Build and Run

    steps:

    - checkout: self

    # Build Docker Image
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        repository: $(imageName)
        dockerfile: '$(Build.SourcesDirectory)/devops-life-app/Dockerfile'
        tags: |
          $(tag)
          latest

    # Show Images
    - task: PowerShell@2
      displayName: Show Docker Images
      inputs:
        targetType: inline
        script: |
          Write-Host "===== Docker Images ====="
          docker images

    # Stop & Remove Existing Container
    - task: PowerShell@2
      displayName: Stop and Remove Existing Container
      inputs:
        targetType: inline
        script: |
          $container = "$(containerName)"

          $exists = docker ps -a --filter "name=$container" --format "{{.Names}}"

          if ($exists) {
              Write-Host "Stopping container..."
              docker stop $container

              Write-Host "Removing container..."
              docker rm $container
          }
          else {
              Write-Host "Container does not exist."
          }

    # Run Container
    - task: PowerShell@2
      displayName: Run Docker Container
      inputs:
        targetType: inline
        script: |
          docker run -d `
            --name $(containerName) `
            -p 8080:80 `
            $(imageName):latest

    # Verify Running Container
    - task: PowerShell@2
      displayName: Verify Docker Container
      inputs:
        targetType: inline
        script: |
          Write-Host "===== Running Containers ====="
          docker ps

          Write-Host "===== Container Logs ====="
          docker logs $(containerName)

    # Success Message
    - task: PowerShell@2
      displayName: Deployment Success
      inputs:
        targetType: inline
        script: |
          Write-Host ""
          Write-Host "========================================"
          Write-Host "Deployment Successful"
          Write-Host "Application URL:"
          Write-Host "http://localhost:8080"
          Write-Host "========================================"
